//Todo: UN JOVEN MUY AFORTUNADO LOGRO GANAR EL PRIMER PREMIO DE LA LOTERIA (EL SIN TECHO AL QUE COFLA LE DIÓ LA PLATA PARA COMPRAR EL BOLETO), EL SIN TECHO DECIDIO HACER UNA FIESTA PARA PODER CELEBRAR LA SITUACIÓN, EL TIPO TAN ENTUSIASMADO COMPRO UNA MAQUINA QUE SOLAMENTE DEJA PASAR A LOS MAYORES DE EDAD 
//* PROBLEMA A
//*-DEJAR PASAR +18
//*-EL PRIMERO QUE ENTRE DESPUÉS DE LAS 2AM NO PAGA

//!COFLA VUELVE DE LA COMISARIA EXAHUSTO Y DE LO CANSADO QUE ESTABA SE FUE A DORMIR, YA QUE AL DIA SIGUIENTE COMENZABA EL CICLO BASICO DE LA UNIVERSIDAD, EN SU CURSO SON 19 ALUMNOS EN TOTAL, PERO SURGIO UN PROBLEMA QUE COMPLICO UN POQUITO A LA FACULTAD, SE ROMPIÓ EL REGISTRO DE ASISTENCIAS Y DURANTE LOS PROXIMOS 30 DIAS NO SE PODRÁN HACER REGISTROS DE NINGÚN TIPO, POR ENDE LAS CLASES NO PODRAN COMENZAR HASTA QUE ESTO NO ESTE SOLUCIONADO
//*PROBLEMA B 
//* -CREAR MINI-SISTEMA PARA REGISTRAR PRESENTES(P) Y AUSENTES(A)
//*-PASADOS 30 DIAS, MOSTRAR SU SITUACIÓN FINAL DEL ALUMNO
//*-MÁXIMO DE 10% DE AUSENCIAS

//? COFLA FELIZ POR HABER EMPEZADO LAS CLASES VOLVIÓ A SU CASA Y YA TIENE SU PRIMER TAREA DE CALCULO, TIENE QUE HACER VARIOS CALCULOS MATEMATICOS, POR LO QUE LA + - / * VAN A SER DE VITAL IMPORTANCIA, POR LO QUE DEBEMOS CREAR UNA CALCULADORA QUE EFECTUE ESTAS ACCIONES POR NOSOTROS

//*PROBLEMA C
//*- SE DEBERA CREAR UNA CALCULADORA QUE NOS SIMPLIFIQUE EL TRABAJO



